### ISSUE TITLE
Not able to integrate Userlogin with HomePage

### ISSUE THREAD

**Issue by C-Das** [eliezerwohl/ToGoList#27]
When I used $(this).load("home.html"); it is giving XMLHTTP error, then i tried to load the file on onclick from HTML onclick="location.href='test.html'", but it is not updating the user name from JQuery call.

**Comment by eliezerwohl** [comment]
hey, two things.  maybe integrate the integreatWithHomePage() into your $("#startSearch").on("click",function().   instead of of in your html.

ALSO:

your function integreatWithHomePage() targets a id called test. I don't see such a id on your page.  I put a div with the id " test"  and it works fine.

**Comment by C-Das** [comment]
I created a single page. inegrated the userlogin functionalities in the home.html page. This is working fine, except for the already existing user registration issue, which I opened now. It shows the welcome message on the top right of the Navbar
